#!/usr/bin/env python
"""
Chart Summarizer Agent - Generates captions for charts.
"""

from typing import Literal
from langgraph.graph import END
from langgraph.prebuilt import create_react_agent
from langgraph.types import Command
from langfuse import observe

from .shared import State, llm
from ..prompts import agent_system_prompt


chart_summary_agent = create_react_agent(
    llm,
    tools=[],
    prompt=agent_system_prompt(
        "You can only generate image captions. You are working with a researcher colleague "
        "and a chart generator colleague. Your task is to generate a standalone, concise "
        "summary for the provided chart image saved at a local PATH, where the PATH should "
        "be and only be provided by your chart generator colleague. The summary should be "
        "no more than 3 sentences and should not mention the chart itself."
    ),
)


@observe(name="chart_summary_node")
def chart_summary_node(state: State) -> Command[Literal[END]]:
    """
    Chart summary sub-agent node.

    Generates a caption describing the chart generated by the chart generator.
    """
    result = chart_summary_agent.invoke(state)
    print(f"Chart summarizer answer: {result['messages'][-1].content}")
    return Command(
        update={
            "messages": result["messages"],
            "final_answer": result["messages"][-1].content,
        },
        goto=END,
    )
